export const OBJ_LIST_ACTIONS_TYPES = {
  ADD_OBJ: '[REDUX][ADD_OBJ]',
  REMOVE_OBJ: '[REDUX][REMOVE_OBJ]',
}

export const SELECTED_OBJ_TYPES = {
  SET_SELECTION: '[REDUX][SET_SELECTION]',
  REMOVE_SELECTION: '[REDUX][REMOVE_SELECTION]',
  CLEAR_SELECTION: '[REDUX][CLEAR_SELECTION]',
}
